NUM1 = 10
NUM2 = 5
print(NUM1 > NUM2)

NUM1 = 5
NUM2 = 5
print(NUM1 > NUM2)

NUM1 = 20
NUM2 = 15
print(NUM1 > NUM2)

NUM1 = 10
NUM2 = 20
print(NUM1 > NUM2)

NUM1 = 25
NUM2 = 20
print(NUM1 > NUM2)

NUM1 = 30
NUM2 = 25
print(NUM1 > NUM2)

NUM1 = 40
NUM2 = 35
print(NUM1 > NUM2)

NUM1 = 55
NUM2 = 60
print(NUM1 > NUM2)

NUM1 = 70
NUM2 = 50
print(NUM1 > NUM2)

NUM1 = 100
NUM2 = 150
print(NUM1 > NUM2)

NUM1 = 10
NUM2 = 15
print(NUM1 < NUM2)

NUM1 = 20
NUM2 = 10
print(NUM1 < NUM2)

NUM1 = 5
NUM2 = 5
print(NUM1 < NUM2)

NUM1 = 30
NUM2 = 40
print(NUM1 < NUM2)

NUM1 = 50
NUM2 = 60
print(NUM1 < NUM2)

NUM1 = 80
NUM2 = 90
print(NUM1 < NUM2)

NUM1 = 10
NUM2 = 5
print(NUM1 < NUM2)

NUM1 = 15
NUM2 = 30
print(NUM1 < NUM2)

NUM1 = 20
NUM2 = 25
print(NUM1 < NUM2)

NUM1 = 100
NUM2 = 99
print(NUM1 < NUM2)

NUM1 = 10
NUM2 = 5
print(NUM1 >= NUM2)

NUM1 = 5
NUM2 = 5
print(NUM1 >= NUM2)

NUM1 = 15
NUM2 = 10
print(NUM1 >= NUM2)

NUM1 = 20
NUM2 = 30
print(NUM1 >= NUM2)

NUM1 = 25
NUM2 = 20
print(NUM1 >= NUM2)

NUM1 = 30
NUM2 = 30
print(NUM1 >= NUM2)

NUM1 = 40
NUM2 = 35
print(NUM1 >= NUM2)

NUM1 = 55
NUM2 = 60
print(NUM1 >= NUM2)

NUM1 = 70
NUM2 = 50
print(NUM1 >= NUM2)

NUM1 = 100
NUM2 = 150
print(NUM1 >= NUM2)

NUM1 = 10
NUM2 = 15
print(NUM1 <= NUM2)

NUM1 = 20
NUM2 = 10
print(NUM1 <= NUM2)

NUM1 = 5
NUM2 = 5
print(NUM1 <= NUM2)

NUM1 = 30
NUM2 = 40
print(NUM1 <= NUM2)

NUM1 = 50
NUM2 = 60
print(NUM1 <= NUM2)

NUM1 = 80
NUM2 = 90
print(NUM1 <= NUM2)

NUM1 = 10
NUM2 = 5
print(NUM1 <= NUM2)

NUM1 = 5
NUM2 = 5
print(NUM1 <= NUM2)

NUM1 = 30
NUM2 = 25
print(NUM1 <= NUM2)

NUM1 = 100
NUM2 = 100
print(NUM1 <= NUM2)

NUM1 = 10
NUM2 = 15
print(NUM1 != NUM2)

NUM1 = 20
NUM2 = 20
print(NUM1 != NUM2)

NUM1 = 10
NUM2 = 5
print(NUM1 != NUM2)

NUM1 = 30
NUM2 = 30
print(NUM1 != NUM2)

NUM1 = 25
NUM2 = 20
print(NUM1 != NUM2)

NUM1 = 50
NUM2 = 55
print(NUM1 != NUM2)

NUM1 = 70
NUM2 = 70
print(NUM1 != NUM2)

NUM1 = 90
NUM2 = 95
print(NUM1 != NUM2)

NUM1 = 100
NUM2 = 90
print(NUM1 != NUM2)

NUM1 = 10
NUM2 = 10
print(NUM1 == NUM2)

NUM1 = 20
NUM2 = 10
print(NUM1 == NUM2)

NUM1 = 15
NUM2 = 15
print(NUM1 == NUM2)

NUM1 = 30
NUM2 = 30
print(NUM1 == NUM2)

NUM1 = 50
NUM2 = 50
print(NUM1 == NUM2)

NUM1 = 70
NUM2 = 70
print(NUM1 == NUM2)

NUM1 = 90
NUM2 = 90
print(NUM1 == NUM2)

NUM1 = 100
NUM2 = 100
print(NUM1 == NUM2)

NUM1 = 120
NUM2 = 120
print(NUM1 == NUM2)

NUM1 = 10
NUM2 = 20
print(NUM1 == NUM2)
