name = input(" name: ")
surname = input(" surname: ")
age = input("age: " )
number1 = input("number2: " )
number2 = input("number2: " )

print(type(name))
print(type(surname))
print(type(age))
print(type(number1))
print(type(number2))