num1=int(input("enter your number:"))
num2=int(input("enter your number2:"))
num3=int(input("enter your number3:"))
num4=int(input("enter your number4:"))
num5=int(input("enter your number5:"))

for i in range(5):
    num1=int(input("enter your number:"))
    num2=int(input("enter your number2:"))
    num3=int(input("enter your number3:"))
    num4=int(input("enter your number4:"))
    num5=int(input("enter your number5:"))
    print(num1)
    print(num2)
    print(num3)
    print(num4)
    print(num5)
